packages:
  - name: controller
    functions:
      - name: main
        runtime: python:default
        web: true
        environment:
          POSTGRES_STRING: "${POSTGRES_STRING}"
          SECRET_KEY: "${SECRET_KEY}"
          BELVO_SECRET_ID: "${BELVO_SECRET_ID}"
          BELVO_SECRET_KEY: "${BELVO_SECRET_KEY}"
          BELVO_BASE_URL: "${BELVO_BASE_URL}"